package com.personal_dashboard.backend.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * In-memory food composition table — the grounding layer for meal analysis.
 *
 * <p>Before this existed, Stage 2 was asked to recall "USDA per-100 g values" from model
 * memory, which made every macro in the app an unverifiable guess. The pipeline now
 * resolves each identified food to a row here and computes macros arithmetically
 * ({@link NutrientResolver}). The model identifies and portions; it never emits a nutrient.
 *
 * <p><b>Two sources, by precedence.</b>
 * <ol>
 *   <li>{@code CURATED} — hand-authored South Indian composite dishes
 *       ({@code food-reference-indian.json}). Ranked above USDA because they are
 *       dish-level ("sambar") where USDA is ingredient-level, and because USDA has
 *       almost no coverage of this cuisine.</li>
 *   <li>{@code USDA} — SR Legacy, ~7.3k lab-measured foods, public domain
 *       ({@code food-reference-usda.json}, generated by {@code tools/build_food_reference.py}).</li>
 * </ol>
 * A third tier, {@code USER}, is reserved for corrections captured from the review UI;
 * {@link #sourceRank} already ranks it highest so the wiring is a matter of adding rows.
 *
 * <p>Held in memory rather than MongoDB on purpose: ~7.4k immutable rows is a couple of
 * MB, needs no migration or user-scoping, and keeps the eval harness runnable without a
 * database. Revisit only if user corrections need to persist per-account.
 */
@Service
@Slf4j
public class FoodReferenceService {

    private static final String USDA_RESOURCE = "data/food-reference-usda.json";
    private static final String INDIAN_RESOURCE = "data/food-reference-indian.json";

    /** Tokens carrying no discriminative signal in food descriptions. */
    private static final Set<String> STOP_WORDS = Set.of(
            "and", "with", "the", "raw", "fresh", "cooked", "prepared", "style",
            "made", "type", "without", "added", "all", "for", "from", "into", "plain");

    @Getter
    private List<FoodRef> foods = List.of();

    /** Inverted index: token -> foods containing it. Keeps lookup off the full scan path. */
    private Map<String, List<FoodRef>> tokenIndex = Map.of();

    @PostConstruct
    void load() {
        ObjectMapper mapper = new ObjectMapper();
        List<FoodRef> all = new ArrayList<>();
        // Curated first so that, on an otherwise equal score, the dish-level Indian entry
        // wins the stable sort against a generic USDA ingredient row.
        all.addAll(readResource(mapper, INDIAN_RESOURCE, "CURATED"));
        all.addAll(readResource(mapper, USDA_RESOURCE, "USDA"));
        this.foods = Collections.unmodifiableList(all);

        Map<String, List<FoodRef>> index = new HashMap<>();
        for (FoodRef f : all) {
            for (String token : f.searchTokens) {
                index.computeIfAbsent(token, k -> new ArrayList<>()).add(f);
            }
        }
        this.tokenIndex = Collections.unmodifiableMap(index);

        long curated = all.stream().filter(f -> "CURATED".equals(f.source)).count();
        log.info("[FoodReference] loaded {} foods ({} curated, {} USDA), {} index tokens",
                all.size(), curated, all.size() - curated, index.size());
    }

    private List<FoodRef> readResource(ObjectMapper mapper, String path, String source) {
        List<FoodRef> out = new ArrayList<>();
        try (InputStream in = new ClassPathResource(path).getInputStream()) {
            JsonNode root = mapper.readTree(in);
            for (JsonNode node : root.path("foods")) {
                FoodRef f = FoodRef.from(node, source);
                if (f != null) out.add(f);
            }
        } catch (Exception e) {
            // A missing USDA bundle degrades match quality but must not stop the app —
            // the curated table alone still covers the user's staple diet.
            log.error("[FoodReference] could not load {} ({}). Run tools/build_food_reference.py",
                    path, e.getMessage());
        }
        return out;
    }

    /**
     * Best matches for a free-text food name, highest score first.
     *
     * <p>Scoring is deliberately simple and explainable rather than clever: token overlap
     * against name + aliases, weighted so that an exact alias hit dominates. Anything
     * fuzzier would be hard to debug when a meal resolves oddly, and the model already
     * emits reasonably canonical names.
     *
     * @return up to {@code limit} matches; empty if nothing scored above the floor
     */
    public List<FoodMatch> search(String query, int limit) {
        Set<String> queryTokens = tokenize(query);
        if (queryTokens.isEmpty()) return List.of();

        // Only consider foods sharing at least one token — avoids scanning 7.4k rows.
        Set<FoodRef> candidates = new HashSet<>();
        for (String token : queryTokens) {
            List<FoodRef> hits = tokenIndex.get(token);
            if (hits != null) candidates.addAll(hits);
        }
        if (candidates.isEmpty()) return List.of();

        String normalizedQuery = normalize(query);
        // Rank on the UNCLAMPED score. Several strong signals can each push a row past
        // 1.0, and clamping before the sort would flatten exactly the distinctions that
        // matter — "Bacon, pork, cooked" and "Bacon, meatless" both saturate otherwise.
        record Scored(FoodRef food, double raw) {}
        List<Scored> scored = new ArrayList<>();
        for (FoodRef f : candidates) {
            double raw = score(f, queryTokens, normalizedQuery);
            if (raw >= 0.30) scored.add(new Scored(f, raw));
        }
        scored.sort((a, b) -> {
            int byScore = Double.compare(b.raw(), a.raw());
            if (byScore != 0) return byScore;
            return Integer.compare(sourceRank(b.food().source), sourceRank(a.food().source));
        });

        List<FoodMatch> out = new ArrayList<>();
        for (Scored s : scored.subList(0, Math.min(limit, scored.size()))) {
            out.add(new FoodMatch(s.food(), Math.min(1.0, s.raw())));
        }
        return out;
    }

    /** Convenience for the resolver: single best match, or null. */
    public FoodMatch bestMatch(String query) {
        List<FoodMatch> matches = search(query, 1);
        return matches.isEmpty() ? null : matches.get(0);
    }

    private double score(FoodRef food, Set<String> queryTokens, String normalizedQuery) {
        // An exact alias match is as strong a signal as this data offers, so it must
        // dominate. These return values sit deliberately above the additive path's
        // realistic ceiling (~1.4): ranking happens on the unclamped score, so returning
        // a flat 1.0 here would let a heavily-bonused USDA row outrank an exact curated
        // alias — "curd" would resolve to a USDA yogurt row instead of the curated entry.
        for (String alias : food.aliases) {
            if (alias.equals(normalizedQuery)) return 2.0;
        }
        for (String alias : food.aliases) {
            if (normalizedQuery.contains(alias) && alias.length() >= 4) return 1.8;
        }

        long overlap = queryTokens.stream().filter(food.searchTokens::contains).count();
        if (overlap == 0) return 0.0;

        // How much of what the user asked for is covered. Note this is deliberately NOT
        // balanced against the food's own token count: USDA's canonical descriptions are
        // long ("Chicken, broilers or fryers, breast, meat only, cooked, roasted") while
        // its oddities are short ("Bacon, meatless"). Rewarding brevity picked the
        // oddities every time — "bacon" resolved to meatless bacon, "sweet potato" to
        // sweet potato leaves, "chicken" to chicken bratwurst.
        double score = (double) overlap / queryTokens.size();

        // The head term is what a USDA description is actually about; everything after
        // the first comma is qualifiers. "Bratwurst, chicken" is a bratwurst.
        if (!food.headToken.isEmpty()) {
            score += queryTokens.contains(food.headToken) ? 0.25 : -0.12;
        }

        // The strongest available signal for canonical-ness: the query accounts for the
        // whole of the row's leading segment ("broccoli" vs "Broccoli, raw" -> yes;
        // vs "Broccoli raab, cooked" -> no, "raab" is unaccounted for). This is what
        // separates the canonical entry from its many near-duplicate cousins, which token
        // overlap alone cannot do — SR Legacy has dozens of rows per common food.
        if (!food.headSegmentTokens.isEmpty() && queryTokens.containsAll(food.headSegmentTokens)) {
            score += 0.30;
        }

        // Mild length discipline: among rows that cover the query equally, prefer the
        // less qualified one. Small enough that it cannot outweigh the head-term signal.
        int extraTokens = Math.max(0, food.searchTokens.size() - queryTokens.size());
        score -= Math.min(0.15, extraTokens * 0.015);

        // Food on a plate has generally been cooked. USDA carries both states for most
        // ingredients and they differ enormously by water loss — raw broccoli is 34
        // kcal/100 g against ~55 cooked, and the gap is far wider for grains and pulses.
        boolean queryImpliesRaw = normalizedQuery.contains("raw")
                || normalizedQuery.contains("fresh") || normalizedQuery.contains("salad");
        if (food.rawForm && !queryImpliesRaw) score -= 0.10;
        if (food.cookedForm && !queryImpliesRaw) score += 0.08;

        // Descriptions that qualify the food into something the user almost certainly did
        // not mean, unless they asked for it explicitly.
        for (String marker : ODD_FORM_MARKERS) {
            if (food.normalizedName.contains(marker) && !normalizedQuery.contains(marker)) {
                score -= 0.20;
            }
        }

        // Curated dish-level rows are the better answer for Indian meals, where a USDA
        // row would otherwise match a single raw ingredient of the same name.
        if ("CURATED".equals(food.source)) score += 0.12;

        // Deliberately NOT clamped to 1.0 — see the ranking note in search().
        return Math.max(0.0, score);
    }

    /**
     * Forms that are technically the queried food but almost never what was on the plate.
     * Each is only penalised when the query did not ask for it.
     */
    private static final List<String> ODD_FORM_MARKERS = List.of(
            // preparation states nobody photographs
            "meatless", "frozen", "dehydrated", "dried", "powder", "canned", "unprepared",
            "concentrate", "substitute", "imitation", "flour", "juice", "syrup", "extract",
            "sprouted", "freeze", "candied", "glutinous", "condensed", "instant",
            // plant parts that are not the part people eat as the named food
            "leaves", "leaf", "raab", "stalk", "shoots", "sprouts and", "seeds", "peel",
            // offal and trim: technically the animal, never the dish
            "feet", "neck", "gizzard", "giblets", "liver", "skin", "heart", "tongue",
            "brain", "kidneys", "tail", "bone", "sticks", "spread", "loaf");

    private static int sourceRank(String source) {
        return switch (source) {
            case "USER" -> 3;
            case "CURATED" -> 2;
            default -> 1;
        };
    }

    static String normalize(String s) {
        return s == null ? "" : s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9 ]", " ")
                .replaceAll("\\s+", " ").trim();
    }

    static Set<String> tokenize(String s) {
        Set<String> out = new HashSet<>();
        for (String t : normalize(s).split(" ")) {
            if (t.length() >= 3 && !STOP_WORDS.contains(t)) out.add(t);
        }
        return out;
    }

    // ─── Types ────────────────────────────────────────────────────────────────

    /** One row of the composition table. Immutable; values are per 100 g. */
    @Getter
    public static class FoodRef {
        String id;
        String name;
        String source;
        boolean vegetarian = true;
        Double glycemicIndex;
        Map<String, Double> per100g;
        List<String> aliases;
        List<Portion> portions;
        Set<String> searchTokens;
        /** Normalized full name, for substring checks against qualifier markers. */
        String normalizedName;
        /** First word of the description — what the row is fundamentally about. */
        String headToken;
        /** Tokens of the leading comma segment, i.e. the food before its qualifiers. */
        Set<String> headSegmentTokens;
        boolean rawForm;
        boolean cookedForm;

        static FoodRef from(JsonNode node, String source) {
            JsonNode per100 = node.path("per100g");
            if (!per100.has("kcal")) return null;

            FoodRef f = new FoodRef();
            f.id = node.path("id").asText();
            f.name = node.path("name").asText();
            f.source = source;
            f.vegetarian = !node.has("veg") || node.path("veg").asBoolean(true);
            f.glycemicIndex = node.has("gi") ? node.path("gi").asDouble() : null;

            Map<String, Double> values = new HashMap<>();
            per100.fields().forEachRemaining(e -> values.put(e.getKey(), e.getValue().asDouble()));
            f.per100g = Collections.unmodifiableMap(values);

            List<String> aliases = new ArrayList<>();
            for (JsonNode a : node.path("aliases")) aliases.add(normalize(a.asText()));
            f.aliases = Collections.unmodifiableList(aliases);

            List<Portion> portions = new ArrayList<>();
            for (JsonNode p : node.path("portions")) {
                portions.add(new Portion(p.path("label").asText(),
                        p.path("grams").asDouble(),
                        p.path("default").asBoolean(false)));
            }
            f.portions = Collections.unmodifiableList(portions);

            Set<String> tokens = tokenize(f.name);
            for (String a : aliases) tokens.addAll(tokenize(a));
            f.searchTokens = Collections.unmodifiableSet(tokens);

            f.normalizedName = normalize(f.name);
            String[] words = f.normalizedName.split(" ");
            f.headToken = words.length > 0 ? words[0] : "";
            f.headSegmentTokens = tokenize(f.name.split(",")[0]);
            f.rawForm = f.normalizedName.contains("raw");
            f.cookedForm = f.normalizedName.contains("cooked")
                    || f.normalizedName.contains("boiled") || f.normalizedName.contains("roasted")
                    || f.normalizedName.contains("baked") || f.normalizedName.contains("steamed")
                    || f.normalizedName.contains("grilled") || f.normalizedName.contains("fried");
            return f;
        }

        public double per100g(String nutrient) {
            return per100g.getOrDefault(nutrient, 0.0);
        }

        /** Grams for the default household portion, or 0 if none is defined. */
        public double defaultPortionGrams() {
            for (Portion p : portions) if (p.isDefault()) return p.grams();
            return portions.isEmpty() ? 0 : portions.get(0).grams();
        }
    }

    /** A household measure and its gram weight, e.g. "1 idli, standard" -> 55 g. */
    public record Portion(String label, double grams, boolean isDefault) {}

    /** A scored match. {@code score} is 0–1; ≥0.9 is an alias-level hit. */
    public record FoodMatch(FoodRef food, double score) {}
}
