package com.personal_dashboard.backend.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.personal_dashboard.backend.dto.GeminiAnalysisResult;
import com.personal_dashboard.backend.service.nutrition.*;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpStatusCodeException;
import org.springframework.web.multipart.MultipartFile;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Orchestrates meal analysis.
 *
 * <h2>Why the pipeline is shaped this way</h2>
 *
 * <p>The previous design asked one model to identify food, recall USDA nutrient values from
 * memory, perform the arithmetic, apply clinical thresholds, score the meal, and write advice —
 * emitting a long chain-of-thought scratchpad along the way. That is expensive in exactly the
 * wrong place (output tokens bill at six times input on Gemini 3.5 Flash) and weak in exactly
 * the place that matters: published evaluations attribute the large majority of LLM nutrition
 * error to incorrect nutrient recall, and none at all to arithmetic.</p>
 *
 * <p>So the work is split by what each component is actually good at:</p>
 * <ol>
 *   <li><b>Vision (paid).</b> Identify ingredients and estimate gram weights. Structurally
 *       barred from emitting nutrition numbers by its response schema.</li>
 *   <li><b>Lookup and arithmetic (free).</b> {@link MacroCalculator} resolves each ingredient
 *       against USDA data and computes exact totals.</li>
 *   <li><b>Clinical rules (free).</b> {@link ClinicalRuleEngine} applies AHA/ADA/KDOQI
 *       thresholds — comparisons, not reasoning — deterministically.</li>
 *   <li><b>Narrative (paid, small).</b> The model explains the findings and suggests swaps,
 *       given the computed facts. No numbers to invent, so a short response suffices.</li>
 * </ol>
 *
 * <p>Both paid stages sit behind a content-addressed cache, so a repeated meal costs nothing.</p>
 */
@Service
@Slf4j
public class NutritionPipelineService {

    private static final String DISCLAIMER =
            "This analysis is generated by an AI system using USDA FoodData Central composition "
            + "data. Nutrient values are looked up rather than estimated, but portion weights are "
            + "visually estimated and carry meaningful uncertainty. It is a decision-support tool "
            + "and does not constitute personalised medical advice. Consult a Registered Dietitian "
            + "or your physician before making significant dietary changes, especially with active "
            + "medical conditions.";

    private final VisionProvider primaryProvider;
    private final VisionProvider fallbackProvider;
    private final MacroCalculator macroCalculator;
    private final ClinicalRuleEngine ruleEngine;
    private final MealAnalysisCacheService cache;
    private ObjectMapper objectMapper;

    public NutritionPipelineService(
            @Qualifier("geminiVisionProvider") VisionProvider primaryProvider,
            @Qualifier("groqVisionProvider") VisionProvider fallbackProvider,
            MacroCalculator macroCalculator,
            ClinicalRuleEngine ruleEngine,
            MealAnalysisCacheService cache) {
        this.primaryProvider = primaryProvider;
        this.fallbackProvider = fallbackProvider;
        this.macroCalculator = macroCalculator;
        this.ruleEngine = ruleEngine;
        this.cache = cache;
    }

    @PostConstruct
    private void init() {
        this.objectMapper = new ObjectMapper();
        this.objectMapper.configure(com.fasterxml.jackson.core.JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS, true);
        this.objectMapper.configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    }

    /**
     * Runs the full pipeline.
     *
     * @param imageFile       optional uploaded image
     * @param textDescription optional free-text description
     * @param ctx             the user's targets, real consumed-today totals, and conditions
     */
    public GeminiAnalysisResult analyze(MultipartFile imageFile,
                                        String textDescription,
                                        NutritionContext ctx) throws Exception {

        byte[] imageBytes = (imageFile != null && !imageFile.isEmpty()) ? imageFile.getBytes() : null;

        // ── 1. Vision extraction (cached by image + description) ───────────
        String extractionKey = cache.extractionKey(imageBytes, textDescription);
        Optional<String> cachedExtraction = cache.get(extractionKey);

        String extractionJson;
        boolean extractionFromCache = cachedExtraction.isPresent();
        if (extractionFromCache) {
            extractionJson = cachedExtraction.get();
        } else {
            extractionJson = call(imageBytes, buildExtractionPrompt(textDescription),
                    GenerationOptions.builder()
                            .stageLabel("extraction")
                            // Perception, not deliberation — shallow thinking is enough and
                            // thinking tokens bill at the output rate.
                            .thinkingLevel("low")
                            // ~560 image tokens instead of ~1120 at high; food photographs
                            // do not need the fine-text tier.
                            .mediaResolution("media_resolution_medium")
                            .maxOutputTokens(2048)
                            .responseSchema(GeminiSchemas.extraction())
                            .build());
            cache.put(MealAnalysisCacheService.KIND_EXTRACTION, extractionKey, extractionJson);
        }

        Stage1Extraction extraction = objectMapper.readValue(extractionJson, Stage1Extraction.class);
        log.info("[NutritionPipeline] Extraction {} — {} ingredient(s)",
                extractionFromCache ? "(cached)" : "complete", extraction.getIngredients().size());

        // ── 2. Deterministic nutrition — no model involved ─────────────────
        ComputedNutrition computed = macroCalculator.compute(extraction);

        // ── 3. Deterministic clinical rules ────────────────────────────────
        List<GeminiAnalysisResult.ClinicalFlag> flags = ruleEngine.evaluate(computed, ctx);
        GeminiAnalysisResult.DailyBudgetAnalysis budget = ruleEngine.budget(computed, ctx);
        GeminiAnalysisResult.MealScore score = ruleEngine.score(computed, ctx, flags);

        // ── 4. Narrative (cached by extraction + profile + findings) ───────
        String flagSignature = flags.stream()
                .map(f -> f.getSeverity() + ":" + f.getTitle())
                .reduce("", (a, b) -> a + "|" + b);
        String narrativeKey = cache.narrativeKey(extractionJson, ctx, flagSignature);

        NarrativeResponse narrative;
        boolean narrativeFromCache;
        Optional<String> cachedNarrative = cache.get(narrativeKey);
        if (cachedNarrative.isPresent()) {
            narrativeFromCache = true;
            narrative = objectMapper.readValue(cachedNarrative.get(), NarrativeResponse.class);
        } else {
            narrativeFromCache = false;
            String narrativeJson = call(null, buildNarrativePrompt(extraction, computed, ctx, flags, score),
                    GenerationOptions.builder()
                            .stageLabel("narrative")
                            // Advice quality benefits from deliberation, and there is no
                            // arithmetic left for it to get wrong.
                            .thinkingLevel("medium")
                            .maxOutputTokens(2048)
                            .responseSchema(GeminiSchemas.narrative())
                            .build());
            narrative = objectMapper.readValue(narrativeJson, NarrativeResponse.class);
            cache.put(MealAnalysisCacheService.KIND_NARRATIVE, narrativeKey, narrativeJson);
        }

        log.info("[NutritionPipeline] Complete — {} kcal, GL {}, {} flag(s), cache: extraction={} narrative={}",
                Math.round(computed.getTotals().getKcal()), computed.getGlycaemicLoad(),
                flags.size(), extractionFromCache, narrativeFromCache);

        return assemble(extraction, computed, ctx, flags, budget, score, narrative,
                extractionFromCache && narrativeFromCache);
    }

    /** Invokes the primary provider, falling back to Groq when Gemini is rate-limited or down. */
    private String call(byte[] imageBytes, String prompt, GenerationOptions options) {
        try {
            return primaryProvider.analyzeFoodImage(imageBytes, prompt, options);
        } catch (HttpClientErrorException.TooManyRequests e) {
            log.warn("[NutritionPipeline] Gemini rate-limited; falling back to Groq.");
            return fallbackProvider.analyzeFoodImage(imageBytes, prompt, options);
        } catch (HttpStatusCodeException e) {
            int status = e.getStatusCode().value();
            if (status == 429 || status == 503) {
                log.warn("[NutritionPipeline] Gemini unavailable ({}); falling back to Groq.", status);
                return fallbackProvider.analyzeFoodImage(imageBytes, prompt, options);
            }
            throw e;
        }
    }

    // =========================================================================
    //  PROMPTS
    //
    //  Both prompts put their invariant instruction block first and all variable
    //  content last. At this workload's request rate the implicit context cache
    //  will rarely be warm, but the ordering costs nothing and is what lets the
    //  cache engage if traffic ever becomes bursty or multi-user.
    // =========================================================================

    /**
     * Vision prompt. Concentrates its budget on the two things the model is measurably good
     * at and that dominate downstream error: identifying what is present, and judging how much.
     *
     * <p>Portion size, not nutrient composition, is the largest error source in image-based
     * dietary assessment, which is why the reference-object guidance below is the longest
     * section rather than an afterthought. Nothing here describes the output format — the
     * response schema handles that.</p>
     */
    private String buildExtractionPrompt(String textDescription) {
        String staticBlock = """
                You are a clinical dietitian and USDA FoodData Central taxonomy expert.
                Your only job is to identify every ingredient in a meal and estimate its weight.
                You do NOT compute calories or macros — that happens downstream from a nutrient
                database, so an invented number here would corrupt a real health record.

                NAMING
                Map every ingredient to its closest USDA FoodData Central description, using FDC
                phrasing: "Rice, white, long-grain, regular, enriched, cooked" — not "white rice".
                Always state the cooked/raw state, because it changes energy density several-fold.
                Give fdc_id only when you are confident; omit it otherwise.

                PORTION ESTIMATION — THIS IS THE HARDEST AND MOST IMPORTANT PART
                Portion error dominates the accuracy of the whole analysis. Work from reference
                objects visible in the frame rather than impressions:
                  - Standard dinner plate rim: 26-28 cm. Quarter plate: 6-7 cm.
                  - Indian katori: 150 ml. Rice bowl: 350 ml. Teaspoon: 5 ml. Tablespoon: 15 ml.
                  - A closed adult fist is about 350 ml; a cupped palm about 100 ml.
                  - Cutlery, phones, and hands in frame are all usable scale references.
                Estimate the volume the food occupies, then convert using its density: cooked rice
                is about 0.8 g/ml, dal or curry about 1.0 g/ml, leafy greens about 0.3 g/ml.
                Give confidence_range_g as a genuine plausible range — at least plus or minus 15%,
                wider when the shot is angled, occluded, or the container's depth is unclear.
                Do not anchor on round numbers.

                HIDDEN INGREDIENTS — YOU MUST INFER THESE
                Cooked food contains ingredients the camera cannot see. Omitting them
                systematically understates energy and sodium. Mark each one is_hidden: true.
                  - Any sauteed, fried, or tempered dish: cooking fat, 5-15 ml per serving.
                  - Any savoury cooked dish: salt, 0.5-2 g per serving. Zero-sodium home
                    cooking is not physiologically plausible.
                  - South Indian (dosa, idli, vada, sambar, upma, pongal): salt in the batter,
                    tempering oil, mustard seeds, curry leaves. Sambar adds tamarind and
                    sambar powder. Coconut chutney carries coconut fat.
                  - Curries and gravies: 10-20 ml oil or ghee in the masala base, plus onion,
                    tomato and ginger-garlic paste where a base is implied. Thai curries add
                    100-150 ml coconut milk.
                  - Biryani and pulao: 10-20 ml ghee or oil, whole spices, salt.
                  - Roti and paratha: 3-8 g cooking fat per piece.
                  - Eggs: 5-10 g butter or oil, plus salt.
                  - Dressed salads: 1-2 tbsp oil.
                  - Commercial bread: roughly 250 mg sodium per slice.

                HONESTY
                If you cannot identify something confidently, still include it and set a low
                confidence_score with a note. Never omit an item to avoid being wrong, and never
                report a weight of zero for a dish that was cooked with fat or salt.
                Record any image quality problems or image/text conflicts in extraction_notes.
                """;

        String dynamicBlock = (textDescription != null && !textDescription.isBlank())
                ? """

                  USER DESCRIPTION OF THIS MEAL
                  "%s"
                  Treat this as a strong signal for resolving ambiguity — protein type, regional
                  style, cooking method. If it contradicts what the image plainly shows, follow
                  the image and record the conflict in extraction_notes.
                  """.formatted(textDescription.trim())
                : "\n\nNo text description was provided. Work from the image alone.";

        return staticBlock + dynamicBlock;
    }

    /**
     * Narrative prompt. Hands the model finished arithmetic and asks only for interpretation.
     *
     * <p>The figures below are stated as established fact precisely so the model does not
     * recompute or second-guess them — that recomputation was the bulk of the old output bill.</p>
     */
    private String buildNarrativePrompt(Stage1Extraction extraction,
                                        ComputedNutrition n,
                                        NutritionContext ctx,
                                        List<GeminiAnalysisResult.ClinicalFlag> flags,
                                        GeminiAnalysisResult.MealScore score) {
        String staticBlock = """
                You are a board-certified clinical dietitian writing for a patient who will read
                this directly, and possibly for their physician.

                All nutrition figures below were computed deterministically from USDA FoodData
                Central composition data. They are correct and final. Do not recalculate them,
                do not restate them as your own estimates, and do not contradict them. The
                clinical flags were produced by a rule engine applying published thresholds.

                Your job is the part arithmetic cannot do: explain what these numbers mean for
                this specific person, and tell them what to do next.

                Requirements:
                  - Recommendations must be specific and quantified. "Eat healthier" is useless.
                    "Swap 150 g white rice for 150 g cooked millet to cut glycaemic load from 33
                    to about 14" is what we want.
                  - Every claim must rest on a mechanism or a named guideline (WHO, AHA, ADA,
                    NICE, KDOQI). Do not invent warnings and do not soften real ones.
                  - Refined carbohydrate — white rice, maida, fruit juice, sugary drinks — drives
                    a genuine insulin response. Say so plainly rather than calling it fine in
                    moderation. The goal is physiological accuracy, not moralising about food.
                  - Acknowledge good things in the meal honestly; do not manufacture praise.
                  - Where portion uncertainty is wide, say the estimate is approximate rather
                    than implying precision the photograph cannot support.
                """;

        StringBuilder facts = new StringBuilder("\n\nMEAL: ")
                .append(extraction.getMealLabel())
                .append(" (").append(extraction.getCuisineType()).append(")\n");

        NutrientProfile t = n.getTotals();
        facts.append(String.format("""

                COMPUTED NUTRITION (authoritative)
                  Energy        : %.0f kcal  (portion-uncertainty range %.0f-%.0f kcal)
                  Protein       : %.1f g
                  Carbohydrate  : %.1f g  (net of fibre: %.1f g)
                  Fat           : %.1f g  (saturated %.1f g)
                  Fibre         : %.1f g
                  Sugars        : %.1f g
                  Sodium        : %.0f mg
                  Potassium     : %.0f mg
                  Glycaemic load: %.1f  (%s)
                  Data confidence: %.0f%% of energy backed by a measured USDA record
                """,
                t.getKcal(), n.getCaloriesLow(), n.getCaloriesHigh(),
                t.getProtein(), t.getCarbs(), t.netCarbs(),
                t.getFat(), t.getSatFat(), t.getFiber(), t.getSugar(),
                t.getSodium(), t.getPotassium(),
                n.getGlycaemicLoad(), n.getGlClassification(),
                n.getDataConfidence() * 100));

        facts.append("\nINGREDIENTS\n");
        for (ComputedNutrition.Item item : n.getItems()) {
            facts.append(String.format("  - %s, %.0f g%s: %.0f kcal, P %.1f g, C %.1f g, F %.1f g, Na %.0f mg%s%n",
                    item.getCommonName() != null ? item.getCommonName() : item.getName(),
                    item.getGrams(),
                    item.isHidden() ? " (hidden/inferred)" : "",
                    item.getNutrients().getKcal(), item.getNutrients().getProtein(),
                    item.getNutrients().getCarbs(), item.getNutrients().getFat(),
                    item.getNutrients().getSodium(),
                    item.isResolved() ? "" : "  [NOT MATCHED — excluded from totals]"));
        }

        facts.append(String.format("""

                THIS PERSON
                  %d-year-old %s, %.0f cm, %.1f kg, BMI %.1f, activity %s
                  Goal: %s.  TDEE %.0f kcal/day.
                  Conditions: %s
                  Daily targets: %.0f kcal, %.0f g protein, %.0f g carbs, %.0f g fat, %.0f mg sodium
                  Already eaten today before this meal: %.0f kcal, %.0f g protein, %.0f mg sodium
                  Remaining after this meal: %.0f kcal, %.0f g protein
                """,
                ctx.getAge(), ctx.getBiologicalSex(), ctx.getHeightCm(), ctx.getWeightKg(),
                ctx.getBmi(), ctx.getActivityLevel(), ctx.getPrimaryGoal(), ctx.getTdee(),
                ctx.getMedicalConditions().isEmpty() ? "None reported"
                        : String.join(", ", ctx.getMedicalConditions()),
                ctx.getGoalCalories(), ctx.getGoalProteinG(), ctx.getGoalCarbsG(),
                ctx.getGoalFatG(), ctx.getGoalSodiumMg(),
                ctx.getConsumedCalories(), ctx.getConsumedProteinG(), ctx.getConsumedSodiumMg(),
                ctx.remainingCalories() - t.getKcal(), ctx.remainingProtein() - t.getProtein()));

        if (flags.isEmpty()) {
            facts.append("\nCLINICAL FLAGS: none triggered.\n");
        } else {
            facts.append("\nCLINICAL FLAGS ALREADY RAISED (address these, do not restate them verbatim)\n");
            for (var f : flags) {
                facts.append(String.format("  - [%s] %s — %s%n",
                        f.getSeverity(), f.getTitle(), f.getQuantifiedRisk()));
            }
        }

        facts.append(String.format("%nMEAL SCORE: %d/100 (grade %s)%n",
                score.getOverallScore(), score.getLetterGrade()));

        if (!n.getUnresolvedIngredients().isEmpty()) {
            facts.append("\nNOTE: these ingredients could not be matched to a nutrient record and "
                    + "are excluded from the totals, so the figures understate the meal: ")
                    .append(String.join(", ", n.getUnresolvedIngredients())).append("\n");
        }

        return staticBlock + facts;
    }

    // =========================================================================
    //  ASSEMBLY
    // =========================================================================

    /** Merges computed figures with model prose into the response contract the UI consumes. */
    private GeminiAnalysisResult assemble(Stage1Extraction extraction,
                                          ComputedNutrition n,
                                          NutritionContext ctx,
                                          List<GeminiAnalysisResult.ClinicalFlag> flags,
                                          GeminiAnalysisResult.DailyBudgetAnalysis budget,
                                          GeminiAnalysisResult.MealScore score,
                                          NarrativeResponse narrative,
                                          boolean fullyCached) {

        NutrientProfile t = n.getTotals();

        var totals = GeminiAnalysisResult.MacroTotals.builder()
                .caloriesKcal(r(t.getKcal(), 0))
                .proteinG(r(t.getProtein(), 1))
                .carbohydratesG(r(t.getCarbs(), 1))
                .fatG(r(t.getFat(), 1))
                .saturatedFatG(r(t.getSatFat(), 1))
                .unsaturatedFatG(r(Math.max(t.getFat() - t.getSatFat(), 0), 1))
                .transFatG(0.0)
                .dietaryFiberG(r(t.getFiber(), 1))
                .sugarG(r(t.getSugar(), 1))
                .addedSugarG(0.0)
                .sodiumMg(r(t.getSodium(), 0))
                .potassiumMg(r(t.getPotassium(), 0))
                .cholesterolMg(r(t.getCholesterol(), 0))
                .caloriesLowKcal(n.getCaloriesLow())
                .caloriesHighKcal(n.getCaloriesHigh())
                // Retained for response-shape compatibility. The gate is now trivially
                // satisfied because the arithmetic is done in Java, not recalled by a model.
                .mathVerification(GeminiAnalysisResult.MathVerification.builder()
                        .expectedCaloriesFromMacros(r(t.atwaterKcal(), 1))
                        .statedCalories(r(t.getKcal(), 0))
                        .deltaKcal(r(t.getKcal() - t.atwaterKcal(), 1))
                        .gatePassed(true)
                        .build())
                .build();

        List<GeminiAnalysisResult.IngredientBreakdown> breakdown = new ArrayList<>();
        for (ComputedNutrition.Item item : n.getItems()) {
            breakdown.add(GeminiAnalysisResult.IngredientBreakdown.builder()
                    .itemId(item.getItemId())
                    .name(item.getName())
                    .commonName(item.getCommonName())
                    .estimatedWeightG(r(item.getGrams(), 0))
                    .isHidden(item.isHidden())
                    .nutritionPer100gSource(item.isResolved()
                            ? (item.isEstimatedComposition()
                                ? "Regional estimate (IFCT/recipe composition)"
                                : "USDA FoodData Central via " + item.getSource())
                            : "Unmatched — excluded from totals")
                    .nutrients(GeminiAnalysisResult.IngredientNutrients.builder()
                            .caloriesKcal(r(item.getNutrients().getKcal(), 0))
                            .proteinG(r(item.getNutrients().getProtein(), 1))
                            .carbohydratesG(r(item.getNutrients().getCarbs(), 1))
                            .fatG(r(item.getNutrients().getFat(), 1))
                            .saturatedFatG(r(item.getNutrients().getSatFat(), 1))
                            .dietaryFiberG(r(item.getNutrients().getFiber(), 1))
                            .sugarG(r(item.getNutrients().getSugar(), 1))
                            .sodiumMg(r(item.getNutrients().getSodium(), 0))
                            .build())
                    .itemMathCheck(GeminiAnalysisResult.ItemMathCheck.builder()
                            .expectedKcal(r(item.getNutrients().atwaterKcal(), 1))
                            .statedKcal(r(item.getNutrients().getKcal(), 0))
                            .passed(true)
                            .build())
                    .glycaemicIndexEstimate(item.getGlycaemicIndex() == null
                            ? null : item.getGlycaemicIndex().doubleValue())
                    .glycaemicLoadContribution(item.getGlycaemicLoadContribution() == null
                            ? null : r(item.getGlycaemicLoadContribution(), 1))
                    .clinicalItemFlags(List.of())
                    .build());
        }

        List<GeminiAnalysisResult.GiOffender> offenders = n.getItems().stream()
                .filter(i -> i.getGlycaemicLoadContribution() != null && i.getGlycaemicLoadContribution() > 1)
                .sorted((a, b) -> Double.compare(b.getGlycaemicLoadContribution(), a.getGlycaemicLoadContribution()))
                .limit(3)
                .map(i -> GeminiAnalysisResult.GiOffender.builder()
                        .ingredientName(i.getCommonName() != null ? i.getCommonName() : i.getName())
                        .giEstimate(i.getGlycaemicIndex() == null ? 0 : i.getGlycaemicIndex())
                        .glContribution(r(i.getGlycaemicLoadContribution(), 1))
                        .clinicalNote(String.format("Contributes %.1f of the meal's %.1f glycaemic load.",
                                i.getGlycaemicLoadContribution(), n.getGlycaemicLoad()))
                        .build())
                .toList();

        var glycaemic = GeminiAnalysisResult.GlycaemicAssessment.builder()
                .totalMealGlycaemicLoad(n.getGlycaemicLoad())
                .glClassification(n.getGlClassification())
                .insulinImpactSummary(narrative.getInsulinImpactSummary())
                .highestGiOffenders(offenders)
                .build();

        List<GeminiAnalysisResult.Recommendation> recommendations = new ArrayList<>();
        int recIndex = 1;
        for (var rec : narrative.getRecommendations()) {
            recommendations.add(GeminiAnalysisResult.Recommendation.builder()
                    .recId(String.format("REC_%03d", recIndex++))
                    .priority(rec.getPriority())
                    .type(rec.getType())
                    .title(rec.getTitle())
                    .action(rec.getAction())
                    .rationale(rec.getRationale())
                    .example(rec.getExample())
                    .conditionTargeted(rec.getConditionTargeted())
                    .build());
        }

        List<GeminiAnalysisResult.PositiveHighlight> highlights = new ArrayList<>();
        int posIndex = 1;
        for (var h : narrative.getPositiveHighlights()) {
            highlights.add(GeminiAnalysisResult.PositiveHighlight.builder()
                    .highlightId(String.format("POS_%03d", posIndex++))
                    .ingredientOrAspect(h.getIngredientOrAspect())
                    .benefit(h.getBenefit())
                    .evidence(h.getEvidence())
                    .build());
        }

        GeminiAnalysisResult.NextMealGuidance nextMeal = null;
        if (narrative.getNextMealGuidance() != null) {
            var g = narrative.getNextMealGuidance();
            nextMeal = GeminiAnalysisResult.NextMealGuidance.builder()
                    .suggestedCalorieRangeKcal(g.getSuggestedCalorieRangeKcal())
                    .priorityNutrientsToTarget(g.getPriorityNutrientsToTarget())
                    .foodsToFavour(g.getFoodsToFavour())
                    .foodsToLimit(g.getFoodsToLimit())
                    .timingRecommendation(g.getTimingRecommendation())
                    .hydrationNote(g.getHydrationNote())
                    .build();
        }

        List<String> dataQuality = new ArrayList<>();
        if (!n.getUnresolvedIngredients().isEmpty()) {
            dataQuality.add("Not matched to a nutrient record, excluded from totals: "
                    + String.join(", ", n.getUnresolvedIngredients()));
        }
        if (!n.getEstimatedIngredients().isEmpty()) {
            dataQuality.add("Composition estimated from regional tables rather than a measured "
                    + "USDA record: " + String.join(", ", n.getEstimatedIngredients()));
        }
        if (extraction.getExtractionNotes() != null && !extraction.getExtractionNotes().isBlank()) {
            dataQuality.add(extraction.getExtractionNotes());
        }
        if (!"Clear".equals(extraction.getImageQuality()) && extraction.getImageQuality() != null) {
            dataQuality.add("Image quality: " + extraction.getImageQuality()
                    + " — portion estimates are correspondingly less certain.");
        }

        return GeminiAnalysisResult.builder()
                .pipelineStage("DETERMINISTIC_USDA_PIPELINE")
                .mealLabel(extraction.getMealLabel())
                .cuisineType(extraction.getCuisineType())
                .mealType(extraction.getMealTypeGuess())
                .analysisTimestampUtc(Instant.now().toString())
                .macroTotals(totals)
                .ingredientsBreakdown(breakdown)
                .glycaemicAssessment(glycaemic)
                .dailyBudgetAnalysis(budget)
                .clinicalFlags(flags)
                .mealScore(score)
                .recommendations(recommendations)
                .positiveHighlights(highlights)
                .nextMealGuidance(nextMeal)
                .dataQualityFlags(dataQuality)
                .dataConfidence(n.getDataConfidence())
                .nutrientSource("USDA_DETERMINISTIC")
                .servedFromCache(fullyCached)
                .disclaimer(DISCLAIMER)
                .build();
    }

    private static double r(double v, int dp) {
        double f = Math.pow(10, dp);
        return Math.round(v * f) / f;
    }
}
